name: Standard Build and Test

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
  push:


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:

  BuildTest:
    runs-on: ubuntu-latest


    container:
      image: cyclus/cyclus-deps_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Building PyNE
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE
          export PATH=/root/.local/bin:/opt/conda/bin:$PATH
          EXPORT CC=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-gcc
          EXPORT CXX=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-g++
          EXPORT CPP=/opt/conda/bin/x86_64-conda_cos6-linux-gnu-cpp
          EXPORT PYTHONPATH="/home/conda/.local/lib/python3.6/site-packages/:/root/.local/lib/python3.6/site-packages/"
          mkdir -p /github/home/.local/lib/python3.6/site-packages/
          ls /github/home/.local/share/cyclus/cyclus_nuc_data.h5
          python install.py -j 2\
                            --build-type=Release \
                            --core-version 999999.999999 \
                            -DBLAS_LIBRARIES="/opt/conda/lib/libblas.so" \
                            -DLAPACK_LIBRARIES="/opt/conda/lib/liblapack.so"
          /github/home/.local/bin/cyclus_unit_tests
