name: Build & Publish docker Cyclus image

on:
  # allows us to run workflows manually
  workflow_dispatch:
  push:
    paths-ignore:
      - 'docker/cyclus-deps/Dockerfile'
      - '.github/workflows/docker_deps_publish.yml'
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  build-img:
    runs-on: ubuntu-latest

    name: Cyclus

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: placing the proper Dockerfile
        run: |
          cp docker/cyclus-ci/Dockerfile .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Export cyclus Docker image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          context: .
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_versions }}
          tags: ghcr.io/${{ github.repository_owner }}/cyclus:ci_testing
      
  test_img:
    needs: [build-img]
    runs-on: ubuntu-latest 

    container:
      image: ghcr.io/${{ github.repository_owner }}/cyclus:ci_testing

    steps:
      - name: Unit Test
        run: |
          cyclus_unit_tests; exit $?
      
      - name: Nosetest
        run: |
          nosetests -w /cyclus/tests; exit $?

  pushing_latest_stable_img:
    if: ${{ github.repository_owner == 'cyclus' }}
    needs: [test_img]
    runs-on: ubuntu-latest

    name: ghcr.io/${{ github.repository_owner }}/cyclus':' ci-testing -> latest/stable

    steps:
      - name: setup
        run: |
          if [ "github.event_name" != "release" ]; then
            echo "img_tag=latest" >> $GITHUB_ENV
          else
            echo "img_tag=stable" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image as stable img
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: ghcr.io/${{ github.repository_owner }}/cyclus:ci_testing
          dst: ghcr.io/${{ github.repository_owner }}/cyclus:${{ env.img_tag }}
